### ISSUE TITLE
Issues Here

### ISSUE THREAD

**Issue by phumiwit** [Carcraftz/MirrorBot#6]
new DiscordAPIError(res.request.path, res.body, res.request.method) : err);
              ^

DiscordAPIError: Cannot send an empty message

how can i solve it?

**Comment by krispykres** [comment]
@phumiwit Did you ever figure this out? Running into the exact same issue

**Comment by KaweGG** [comment]
How did you even get it to work? With me it doesn't do anything lmao

**Comment by WLines84** [comment]
same issue 
C:\Users\whitelines\Desktop\discord bot2\node_modules\discord.js-selfbot-v11\src\client\rest\RequestHandlers\Sequential.js:85
              new DiscordAPIError(res.request.path, res.body, res.request.method) : err);
              ^

DiscordAPIError: Cannot send an empty message
    at C:\Users\whitelines\Desktop\discord bot2\node_modules\discord.js-selfbot-v11\src\client\rest\RequestHandlers\Sequential.js:85:15
    at C:\Users\whitelines\Desktop\discord bot2\node_modules\snekfetch\src\index.js:215:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {

**Comment by BRxwe1** [comment]
Any fixes on this??
